### ISSUE TITLE
Az CLI Login Error

### ISSUE THREAD

**Issue by thepaulmacca** [jongio/github-azure-oidc#3]
Thanks for your work on this Jon, this approach is much better than reading the docs at the moment!

I've hit a bit of a weird issue. I'm deploying bicep files using some reusable workflows https://github.com/ops-to-dev/actions-reusable-workflows/blob/main/.github/workflows/bicep-deploy.yml and the `validate` job logs in fine, but the 'deploy` job fails with the below error:

![image](https://user-images.githubusercontent.com/41340540/144221107-f0e0d772-838c-4869-8907-71681a3092d9.png)

I'm not sure why it works for one job but not the other. I've used the script as-is

This is the workflow that i'm using to call the above workflow:

```yaml
name: deploy-aks-baseline-cluster

on: 
  push:
    branches: 
    - main
    paths:
    - 'deploy/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  # Lint the Bicep file
  lint: 
    uses: ops-to-dev/actions-reusable-workflows/.github/workflows/bicep-lint.yml@main

  # Deploy to the Dev environment
  deploy-dev:
    uses: ops-to-dev/actions-reusable-workflows/.github/workflows/bicep-deploy.yml@main
    needs: lint
    with:
      environmentName: dev
      environmentType: nonprod
      resourceGroupName: rg-aks-tpm-dev-uks
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
```

Do you have any ideas on what the issue could be?

Thanks
